=== AtAltitude/xmlgraphics-fop/docs/examples/svg/Document.dtd
<!--
	XML Document DTD, version 1.00

	document dtd
	should allow for all standard writing of a document, title, author, summary,
	main topics, sub topics, lists, figures, index
-->

<!ELEMENT Document				(Title, Description, Summary?, (Chapter | ExternalChapter)*, Appendix*)>
<!ATTLIST Document				version CDATA #FIXED "1.0">
<!ELEMENT Summary				(Title, ExternalDiagram?, Body)>
<!ELEMENT Appendix				(Title, ExternalDiagram?, Body, Section*)>
<!ELEMENT Chapter				(Title, ExternalDiagram?, Body, Section*)>
<!ELEMENT Section				(Title, ExternalDiagram?, Body, SubSection*)>
<!ELEMENT SubSection			(Title, ExternalDiagram?, Body)>
<!ELEMENT Title					(#PCDATA)>
<!ELEMENT Body					(ExternalDiagram | p)*>
<!ELEMENT p						ANY>
<!ELEMENT ExternalDiagram		(#PCDATA)>
<!ATTLIST ExternalDiagram		file CDATA #REQUIRED
								showcode CDATA #IMPLIED>
<!ELEMENT ExternalSVG			(#PCDATA)>
<!ATTLIST ExternalSVG			file CDATA #REQUIRED>
<!ELEMENT ExternalChapter		(#PCDATA)>
<!ATTLIST ExternalChapter		file CDATA #REQUIRED>
<!ELEMENT index					(#PCDATA)>
<!ELEMENT br					(#PCDATA)>
<!ELEMENT i						(#PCDATA)>
<!ELEMENT image					(#PCDATA)>
<!ELEMENT a						(#PCDATA)>
<!ELEMENT b						(#PCDATA)>
<!ELEMENT blockquote			(#PCDATA)>
<!ELEMENT code					(#PCDATA)>
<!ELEMENT Version				(#PCDATA)>

=== AtAltitude/xmlgraphics-fop/docs/examples/svg/MoreTests.xml
<?xml version="1.0"?>
<!DOCTYPE Document SYSTEM "Document.dtd">
<Document>
	<Title>More SVG Tests</Title>
	<Description>
	    Some more SVG tests.
	</Description>
	<Chapter>
		<Title>Examples</Title>
		<Section>
			<Title>Introduction</Title>
			<Body>
				<p>
					These examples show the areas of SVG currently implemented.
				</p>
				<p>
					This is provided so that others can see how to write the svg elements
					and the result to expect.
				</p>
			</Body>
		</Section>
		<Section>
			<Title>Graphic Elements</Title>
			<SubSection>
				<Title>Miscellaneous</Title>
				<Body>
					<p>
						Various styles and other drawing things.
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-arc</ExternalDiagram>
						Arcs
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-gradients</ExternalDiagram>
						Gradients
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-paths</ExternalDiagram>
						Paths
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-radial</ExternalDiagram>
						Radial
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-rotate</ExternalDiagram>
						Rotations
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-rototext</ExternalDiagram>
						Rotated text
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-shapes</ExternalDiagram>
						Shapes
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-stroke</ExternalDiagram>
						Strokes
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-test</ExternalDiagram>
						Tests
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-transform</ExternalDiagram>
						Transforms
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-opac</ExternalDiagram>
						Opacity
					</p>
				</Body>
			</SubSection>
		</Section>
	</Chapter>
</Document>

=== AtAltitude/xmlgraphics-fop/docs/examples/svg/LargeExamples.xml
<?xml version="1.0"?>
<!DOCTYPE Document SYSTEM "Document.dtd">
<Document>
	<Title>Large SVG Examples</Title>
	<Description>
	    Some large svg examples which have many shapes.
	</Description>
	<Chapter>
		<Title>Examples</Title>
		<Section>
			<Title>Introduction</Title>
			<Body>
				<p>
					These examples show the areas of SVG currently implemented.
				</p>
				<p>
					This is provided so that others can see how to write the svg elements
					and the result to expect.
				</p>
			</Body>
		</Section>
		<Section>
			<Title>Graphic Elements</Title>
			<SubSection>
				<Title>Miscellaneous</Title>
				<Body>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-lion</ExternalDiagram>
						A lion
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-molecule</ExternalDiagram>
						A molecule
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-newlion</ExternalDiagram>
						Another lion
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-picasso</ExternalDiagram>
						A Picasso picture
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-svglogo</ExternalDiagram>
						The SVG View logo
					</p>
					<p>
						<ExternalDiagram file="misc-diagrams.xml">misc-tiger</ExternalDiagram>
						A tiger
					</p>
					<p>
						<ExternalDiagram file="apache-diagrams.xml">apache-foplogo</ExternalDiagram>
						FOP logo in SVG.
					</p>
					<p>
						<ExternalDiagram file="apache-diagrams.xml">apache-xml</ExternalDiagram>
						Apache logo in SVG.
					</p>
					<p>
						<ExternalDiagram file="mozilla-diagrams.xml">mozilla-xml</ExternalDiagram>
						Mozilla logo in SVG.
					</p>
				</Body>
			</SubSection>
		</Section>
	</Chapter>
</Document>

=== AtAltitude/xmlgraphics-fop/docs/examples/svg/UnitTests.xml
<?xml version="1.0"?>
<!DOCTYPE Document SYSTEM "Document.dtd">
<Document>
	<Title>Unit Tests for SVG in FO</Title>
	<Description>
	    Some unit tests to check out the rendering of svg.
	</Description>
	<Chapter>
		<Title>Examples</Title>
		<Section>
			<Title>Introduction</Title>
			<Body>
				<p>
					These examples show the areas of SVG currently implemented.
				</p>
				<p>
					This is provided so that others can see how to write the svg elements
					and the result to expect.
				</p>
			</Body>
		</Section>
		<Section>
			<Title>Graphic Elements</Title>
			<SubSection>
				<Title>Miscellaneous</Title>
				<Body>
					<p>
						<ExternalSVG file="test/initialCoords.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/nested.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/origCoordSys.svg"/>
						unit test
					</p>
<!--					<p>
						<ExternalSVG file="test/preserveAspectRatio.svg"/>
						unit test
					</p>-->
					<p>
						<ExternalSVG file="test/rotateScale.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/skew.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/transformTest.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/units.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/viewBox1.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/viewBox2.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/newCoordSys.svg"/>
						unit test
					</p>
<!--					<p>
						<ExternalSVG file="test/newCSSUnits.svg"/>
						unit test
					</p>-->
					<p>
						<ExternalSVG file="test/newViewport.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/molecule.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/junk.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/use01.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/use02.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/use03.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/shapes.svg"/>
						unit test
					</p>
					<p>
						<ExternalSVG file="test/arcs.svg"/>
						Arcs using the arc command in the path data.
					</p>
				</Body>
			</SubSection>
		</Section>
	</Chapter>
</Document>

=== AtAltitude/xmlgraphics-fop/docs/examples/svg/Misc.xml
<?xml version="1.0"?>
<!DOCTYPE Document SYSTEM "Document.dtd">
<Document>
	<Title>Miscellaneous SVG Examples</Title>
	<Description>
	    Some general svg examples.
	</Description>
	<Chapter>
		<Title>Examples</Title>
		<Section>
			<Title>Introduction</Title>
			<Body>
				<p>
					These examples show the areas of SVG currently implemented.
				</p>
				<p>
					This is provided so that others can see how to write the svg elements
					and the result to expect.
				</p>
			</Body>
		</Section>
		<Section>
			<Title>Graphic Elements</Title>
			<SubSection>
				<Title>Miscellaneous</Title>
				<Body>
					<p>
						Various styles and other drawing things.
					</p>
				</Body>
			</SubSection>
		</Section>
	</Chapter>
</Document>
